title: ELI5 HIPAA
description: Explain Like I'm 5 - HIPAA
theme: just-the-docs

#url: https://just-the-docs.github.io
#baseurl: http://localhost:4000

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
nav_enabled: true

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"


